#apiVersion: operators.coreos.com/v1alpha1
#kind: Subscription
#metadata:
#  name: serverless-operator
#  namespace: openshift-serverless
#spec:
#  channel: stable
#  installPlanApproval: Automatic
#  name: serverless-operator
#  source: redhat-operators
#  sourceNamespace: openshift-marketplace
#  startingCSV: serverless-operator.v1.21.1
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: serverless-operator
  generateName: serverless-operator-
  namespace: openshift-operators
spec:
  installPlanApproval: Automatic
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  name: serverless-operator
  channel: stable